[[constraint]]
  name = "github.com/appscode/jsonpatch"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

# Kubernetes >= 1.10.
# Note: Change all at once.
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"
