[[constraint]]
  name = "github.com/evanphx/json-patch"
  version = "3.0.0"

# Kubernetes >= 1.10.
# Note: Change all at once.
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.5"


[prune]
  go-tests = true
  unused-packages = true
